<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\basket.Core\basket.Core.csproj" />
	 <ProjectReference Include="..\..\..\Infrastructure\EventBus.Messages\EventBus.Messages.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.76.0" />
    <PackageReference Include="MediatR" Version="13.1.0" />
  </ItemGroup>


	<ItemGroup>
		<Protobuf Include="..\..\..\services\discount\discount.Application\Protos\discount.proto" Link="Protos\discount.proto" GrpcServices="Client" />
	</ItemGroup>

</Project>
